/// Flutter icons DataStructure
/// Copyright (C) 2021 by original authors @ fluttericon.com, fontello.com
/// This font was generated by FlutterIcon.com, which is derived from Fontello.
///
/// To use this font, place it in your fonts/ directory and include the
/// following in your pubspec.yaml
///
/// flutter:
///   fonts:
///    - family:  DataStructure
///      fonts:
///       - asset: fonts/DataStructure.ttf
///
/// 
/// * Material Design Icons, Copyright (C) Google, Inc
///         Author:    Google
///         License:   Apache 2.0 (https://www.apache.org/licenses/LICENSE-2.0)
///         Homepage:  https://design.google.com/icons/
///
import 'package:flutter/widgets.dart';

class DataStructure {
  DataStructure._();

  static const _kFontFam = 'DataStructure';
  static const String _kFontPkg = null;

  static const IconData arrow_downward = IconData(0xe800, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData graph = IconData(0xe801, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData hashtable = IconData(0xe802, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData heap = IconData(0xe803, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData linkedlist = IconData(0xe804, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData queue = IconData(0xe805, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData stack = IconData(0xe806, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData structure = IconData(0xe807, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData trees = IconData(0xe808, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData array = IconData(0xe809, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData data = IconData(0xe80a, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData datastructure = IconData(0xe80b, fontFamily: _kFontFam, fontPackage: _kFontPkg);
}
